### PR TITLE
Convert definition to method

### LINKED ISSUE #6: No block given
The more you use this the longer the install can take, so I treid to add a timeout.... but I get:

```
LocalJumpError
--------------
no block given (yield)
```

and it points to this line:

```
 64:    multipackage list_of_packages do
 65:      action :upgrade
 66>>     timeout 480
 67:    end
```

:(

### PR DESCRIPTION
**Pull request by lamont-granquist**
This avoids the problem with params[:timeout] and method_missing in the awful definitions params-hash handler by just not using a definition.

As a bonus, should get a "NoMethodError" at least when someone tries to set a 'tiemout' or some typo like that.

Closes #6

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@jaymzh gonna release this in a day or two, lemme know if you can give it a shot?

**Comment by jaymzh** [comment]
I blocked off an hour tomorrow to test this and your attributes code...

**Comment by jaymzh** [comment]
Doing this breaks our ability to call this from within providers. :(

**Comment by lamont-granquist** [comment]
@jaymzh okay does that fix you?

**Comment by jaymzh** [comment]
Tested - breaks when used from LWRPs still... emailed you stacktraces.

**Pull request closed without merging**
