### PR TITLE
Restructure multipackage a bit

### PR DESCRIPTION
**Pull request by jaymzh**
- Make the definition the default call place
- Rename the LWRP 'internal'
- Handle 'actions'

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Yeah, weird, I'm not sure why I didn't think that would work...

Might have been just too burned out when I was thinking about it...

Gimme a day or so to see if I can remember what I was thinking, then I'll whack merge if I cant come up with anything...

**Comment by jaymzh** [comment]
No worries. When you're happy with it, I'm going to roll this out en-mass here, and I want to wait until this API if set it stone...

Note there _IS_ a risk here... 

If you interlace removal/install/upgrades ... the order will be deinterlaces and you'll get all packages for whatever the first action you used is first, and then all packages for whatever your second action is. So if you do:

```
multipackage ['a', 'b'] do
  action :upgrade
end

multipackage ['c-crufty'] do
  action :remove
end

multipackage ['c'] do
  action :upgrade
end
```

And installing c requires uninstalling c-crufty, then this will fail to work... but that's a side-effect of scatter-gather approaches that work like this.

Moreover you cannot fix this by changing that removal rule to a standard `package` rule - you _have_ to either get your c-crufty rule early, or not use the accumulator for `c`. 

And I think that's acceptable - it's part of understanding the advanced usage here.

**Comment by lamont-granquist** [comment]
Yeah I don't think that's what I was worried about.   You should also be able to do a thunk really early:

``` ruby
multipackage do
  action :remove
end
```

Then all your removes happen early.  Then all the installs should depsolve and succeed...

And if you have weirder issues, then scatter-gather is just the wrong approach...

**Comment by lamont-granquist** [comment]
In fact if you just do something like this as your first recipe:

``` ruby
include_recipe "apt"

multipackage do
  action :remove
end

multipackage do
  action :install
end
```

Then all your removes happen before all your installs, very early, but after `apt-get update` is run.

**Comment by jaymzh** [comment]
Can you do that without names?

**Comment by lamont-granquist** [comment]
I intended for it to work that way.

**Comment by jaymzh** [comment]
sweet. Let's do this then!

**Comment by jaymzh** [comment]
Can we merge this now?

**Comment by jaymzh** [comment]
Pretty please, @lamont-granquist

**Comment by lamont-granquist** [comment]
YOLO

**Comment by lamont-granquist** [comment]
do you need a release or can you pull from github for a bit?

**Comment by jaymzh** [comment]
I always pull from github. Thanks!

**Pull request merged**
